### ISSUE TITLE
curses

### ISSUE THREAD

**Issue by miller-time** [miller-time/rust-warrior#20]
can the game's ui be drawn using curses to redraw the map instead of spamming the terminal? (note: I just want an excuse to use curses, this might not actually be a better user experience)

this could be feature-flagged in the player's Cargo.toml

```toml
[dependencies]
rust-warrior = { version = "0.12.1", features = ["curses"] }
```

when this feature is enabled, the old style of showing every update should be written to `combat.log` so the user can see what went wrong if they die
